import { NextRequest, NextResponse } from 'next/server'
import { getAllTickets, createTicket, getTicketsByStatus } from '@/lib/db-utils'
import { generateTicketId } from '@/lib/db-utils'

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const status = searchParams.get('status')
    const past = searchParams.get('past')
    
    let tickets
    if (status === 'Completed' && past === 'true') {
      // Fetch completed tickets from past dates (not today)
      tickets = await getTicketsByStatus('Completed', true)
    } else if (status) {
      tickets = await getTicketsByStatus(status)
    } else {
      tickets = await getAllTickets()
    }
    
    return NextResponse.json(tickets)
  } catch (error) {
    console.error('Error fetching tickets from database:', error)
    return NextResponse.json(
      { error: 'Failed to fetch tickets' },
      { status: 500 }
    )
  }
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { user_id, concern, details, category, status = 'For Approval' } = body
    
    // ticket_id will be auto-generated by database trigger
    const newTicket = await createTicket({
      ticket_id: '', // Will be auto-generated by database trigger
      user_id,
      concern,
      details,
      category,
      status,
      position: 0,
      profile_picture: null,
      first_name: null,
      last_name: null,
    })
    
    return NextResponse.json(newTicket, { status: 201 })
  } catch (error) {
    console.error('Error creating ticket:', error)
    return NextResponse.json(
      { error: 'Failed to create ticket' },
      { status: 500 }
    )
  }
}